name: Post Commit Status

on:
  workflow_dispatch:
    inputs:
      feature:
        description: 'Feature added'
        required: true
        default: 'null'
        type: string

jobs:
  post-status:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Post commit status
      uses: actions/github-script@v6
      with:
        script: |
          const { data: commit } = await github.rest.repos.getCommit({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: context.sha
          });

          await github.rest.repos.createCommitStatus({
            owner: context.repo.owner,
            repo: context.repo.repo,
            sha: context.sha,
            state: 'success',
            description: `Feature: ${{ github.event.inputs.feature }}`,
            context: 'ci/github-actions'
          });
